notaryproject/notation-core-go

go.mod
x509/cert.go
x509/key.go

* Moving x509 cert, key parsing utilities from notation-go to notation-core-go
* Will raise a separate PR for refactoring notation-go and notation repos
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>

Add x509 parsing utilities

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/reusable-build.yml
.github/workflows/reusable-codeql.yml
.gitignore
Makefile
scripts/test.sh

Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>

Setup Github workflow

---

go.mod
go.sum
internal/crypto/hashutil/hash.go
internal/testhelper/certificatetest.go
signer/errors.go
signer/jws.go
signer/jws_test.go
signer/jwt.go
signer/signer.go
signer/signer_test.go

Change Log:
- Implements SignatureEnvelope struct that would be used by notation-go-lib to generate/verify the signature.
- SignatureEnvelope internally implements actual signature formats like jws(cose in future)
- Implemented JWS-JSON signature generation and verification code.

Abstract out signature generation and verification to SignatureEnvelope

---

signer/types.go
signer/utils.go

Signed-off-by: zaihaoyin <zaihaoyin@microsoft.com>
This PR fixes https://github.com/notaryproject/notation/issues/268.
According to the [plugin spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md), the `hashAlgorithm` field of `GenerateSignatureRequest` should be one of the following strings.
```
// Hash algorithm associated with the key spec, plugin must 
// hash the payload using this hash algorithm
"hashAlgorithm" : "SHA_256" | "SHA_384" | "SHA_512",
```
However, the current implementation uses `crypto.Hash.String()`, which will return a string like `SHA-256` and break the azure-kv plugin.
Also need to update notation-go and notation to make the plugin works.

fix hash function name according to the spec

---

signature/algorithm.go
signature/cose/cose.go
signature/envelope.go
signature/internal/base/envelope.go
signature/jws/jws.go
signature/signer.go
signature/types.go

Refactor `signer` to `signature` submodule so that we can easily integrate COSE to the signing framework.
Note: this PR only exposes the necessary intefaces and basic implementations to help engineers to work on different component parallelly.
And missing comments will be added by the following PRs.

feat: refactor signature envelope to support cose

---

signature/internal/base/envelope.go

Refactor `Verify` so that it just returns the payload and signerInfo from the internal envelope.

refactor: use internal envelope to verify

---

signature/errors.go
signature/signer.go

Add missing VerifyAuthenticity which would be used in `notation-go`.

feat: add missing VerifyAuthenticity

---

signature/algorithm.go
signature/envelope.go
signature/internal/base/envelope.go
signature/jws/signer.go
signature/jws/utils.go

1. Add some shared logics from jws/cose envelope into the base envelope.
2. Add post payload validation in `Payload` method.
3. Add prior certificate chain validation in `Sign` method.
4. Add prior payload validation in `Verify` method.
5. Add exported method to get registered envelope types.

refactor: add common logic to base envelope

---

signature/jws/envelope.go
signature/jws/envelope_test.go
signature/jws/jws.go
signature/jws/jwt.go
signature/jws/types.go

1. Payload() returns the raw payload context instead of base64 encoded data
2. move extract algorithm step from Sign() to getSignedAttrs()
3. wrap the parse error in a MalformedSignatureError

fix: update envelope.Payload() logic

---

signature/types.go

Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

added extended attribute getter for notation-go

---

signature/internal/base/envelope.go
signature/internal/base/envelope_test.go

Fix the workflow in envelope.Sign() so that we validate the certificate chain after signing correctly.

fix: fix the certs validation in envelope.Sign()

---

signature/algorithm.go
signature/algorithm_test.go
signature/cose/envelope_test.go
signature/errors.go
signature/errors_test.go
signature/internal/base/envelope.go
signature/jws/envelope.go
signature/jws/envelope_test.go
signature/jws/jws.go
signature/jws/jws_test.go
signature/jws/jwt.go
signature/jws/jwt_test.go
signature/jws/types.go
signature/jws/types_test.go
signature/signaturetest/algorithm.go
signature/signaturetest/signer.go

1. update to support new signature.Signer
2. update to support new signature.LocalSigner
3. add remoteSigningMethod & localSigningMethod
4. update verifyJWT logic to delegate JWT package to select SigningMethod
5. refector testing structure: extract GetTestLocalSigner() from cose/envelope_test.go to be shared function of testing library in ./signature/signaturetest
Test:
>ok      github.com/notaryproject/notation-core-go/signature/jws         coverage: 96.6% of statements

refector & test: update to support new signature.Signer interface

---

signature/jws/conformance_test.go
signature/jws/testdata/conformance.json

Test the conformance between signed message and original signing request.

add JWS conformance test

---

signature/algorithm.go
signature/algorithm_test.go
signature/envelope.go
signature/envelope_test.go
signature/errors.go
signature/errors_test.go
signature/internal/base/envelope.go
signature/internal/base/envelope_test.go
signature/signer.go
signature/signer_test.go
signature/types.go
testhelper/certificatetest.go

This PR is splitted into https://github.com/notaryproject/notation-core-go/pull/59 and https://github.com/notaryproject/notation-core-go/pull/64 if you'd like to review one by one. I'll sync updates from splitted PRs here.
Background can be checked out in https://github.com/notaryproject/notation/discussions/278
1. Created a new `signature` submodule to refactor the original `signer` submodule. 
2. Created `Envelope` interface.
3. Renamed the original `SignatureProvider` to `Signer`. 
4. Created `LocalSigner` to support native signing implementation provided by underlying crypto libraries, e.g. go-cose, go-jwt.
5. Created `internal.base.Envelope` struct to replace the orginal `SignatureEnvelope` struct.
6. Other refactoring on the algorithm and keySpec definitions.
Added corresponding …

refactor: refactor envelope and signer to support cose

---

signature/errors.go
signature/errors_test.go
signature/jws.go
signature/jws_test.go
signature/jwt.go
signature/jwt_test.go
signature/signer.go
signature/signer_test.go
signature/types.go
signature/utils.go
signature/utils_test.go

1. Rename signer submodule to signature submodule.
2. Update the package name accordingly.

refactor: rename signer to signature submodule

---

.github/workflows/reusable-build.yml
.github/workflows/reusable-codeql.yml
go.mod

Update 
1. go.mod
2. github action
Test:
Unit test work well
Resolves #22 

feat: update to go 1.18

---

signature/errors.go
signature/jws/jwt.go
signature/jws/types.go

refactor: refactor comments

---

signature/cose/conformance_test.go
signature/cose/envelope.go
signature/cose/envelope_test.go
signature/jws/conformance_test.go
signature/jws/jws.go
signature/types.go

Fixed issue #88.
After this update:
1. JWS extended attribute keys still enforce string type.
2. COSE extended attribute keys will accept string and int type.
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

update: updated COSE extended attributes logic

---

testhelper/certificatetest.go
x509/cert_validations_test.go

Signed-off-by: Pritesh Bandi <pritesb@amazon.com>
Issue: https://github.com/notaryproject/notation/issues/429
----------
Time after fix:
```
➜  notation git:(main) ✗ time ./notation version  
Notation: Notary v2, A tool to sign, store, and verify artifacts.
Version:     v0.12.0-beta.1+unreleased
Go version:  go1.19.3
./notation version  0.00s user 0.01s system 30% cpu 0.042 total
➜  notation git:(main) ✗ time ./notation cert list
2022/11/04 18:34:49 Start took 355.927µs
/Users/pritesb/Library/Application Support/notation/truststore/x509/ca/digi-root.pem
/Users/pritesb/Library/Application Support/notation/truststore/x509/ca/temp/digi-root.pem
/Users/pritesb/Library/Application Support/notation/truststore/x509/signingAuthority/temps/digi-root.pem
./notation cert list  0.00s user 0.01s …
```

Lazily create certificates

---

x509/cert.go
x509/cert_validations.go
x509/cert_validations_test.go

This PR would:
resolve #117
resolve #119
resolve #121 
Signed-off-by: Patrick Zheng <patrickzheng@microsoft.com>

fix: updated error messages for certificate chain validation in x509 package

---

.github/workflows/reusable-build.yml
.github/workflows/reusable-codeql.yml
go.mod

Updates go.mod and the GitHub actions to shift window from [1.18, 1.19] to [1.19,1.20]
Confirmed that unit tests work for 1.20
Resolves #115 
Signed-off-by: Kody Kimberl kody.kimberl.work@gmail.com

build: shift Go support window to [1.19, 1.20]

---

revocation/ocsp/ocsp.go

This is a followup fix to #134 
After testing with real certificates, there are some discrepancies with what hashes are supported and the correct URL encoding.
---
The following do not support SHA256 hashes:
- Microsoft
- Entrust
- Let's Encrypt
- Digicert (sometimes)
As this represents a large percentage of public CAs, we should change the hashing algorithm to SHA1, which has been confirmed to be supported by all that were tested.
---
Additionally, the base64 URL encoding was not actually escaping URL characters, resulting in malformed requests. We need to change it to StdEncoding and query escape it.
Signed-off-by: Kody Kimberl kody.kimberl.work@gmail.com

fix: change OCSP hash and encoding

---

README.md
go.mod
go.sum
signature/jws/types.go
signature/types.go

This chore PR resolves #127.
This PR also upgraded dependencies of the library.

chore: updated Notary v2 to Notary Project

---

.github/ISSUE_TEMPLATE/bug-or-issue.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yaml

Add issue template for `notation-core-go`, which is copied from `notation` repo.
Signed-off-by: Yi Zha <yizha1@microsoft.com>

chore: add issue template

---

.github/workflows/reusable-build.yml
.github/workflows/reusable-codeql.yml
go.mod

Since go has released 1.21, moving the build window from [1.19, "1.20"] to ["1.20", "1.21"].

build: shift Go support window to [1.20, 1.21]

---

x509/cert_validations.go
x509/cert_validations_test.go

fix: update key usage error message to make it clear

---

.github/workflows/license-checker.yml
.github/workflows/reusable-license-checker.yml

This PR updates license-checker to the fixed version of skywalking-eyes.
The related discussion: https://github.com/apache/skywalking/discussions/11391

fix: fix license dependency check workflow

---

README.md

doc: update README to align with the new project brand

---

.github/workflows/stale.yml

This PR enables the `notation-core-go` repo to run stale action at 1:30 every day to label or close stale PRs and issues. See guideline https://github.com/marketplace/actions/close-stale-issues
This is the definition for stale PRs or issues that we discussed during community call and to be updated in [contributing PR](https://github.com/notaryproject/.github/pull/25).
"A stale issue is one that remains inactive or without updates for a period of 60 days. A stale pull request (PR) is one that remains inactive or without updates for a period of 45 days. When an issue or PR becomes stale, it is labelled as `stale`. Normally maintainers will comment on stale issues or PRs to prompt participants to take action. If there is no activity for additional 30 days, this issue or PR will be closed. If …

chore: add GitHub action for stale issues and PRs

---

.github/workflows/reusable-build.yml
.github/workflows/reusable-codeql.yml
go.mod

bump: bump up golang version to v1.21

---

.github/workflows/reusable-build.yml

The same issue as: https://github.com/notaryproject/notation/issues/921

fix(ci): update codecov token

---

x509/cert_validations.go
x509/cert_validations_test.go

fix: leaf certificate validation

---

.github/workflows/build.yml
.github/workflows/reusable-build.yml

Fix:
- All the `main` branch build are failed at the step to upload codecov because of lacking of codecov token: https://github.com/notaryproject/notation-core-go/actions/runs/9706110222/job/26789276954#step:5:32
- manually pass CODECOV_TOKEN to reusable-build.yml
Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Will update notation-go, tsp-client after this PR is merged.

fix(ci): pass CODECOV_TOKEN to reusable-build.yml

---

signature/types.go
signature/types_test.go

This PR fixes `signerInfo.AuthenticSigningTime` to return the correct results. 
According to spec: https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md#signing-time--authentic-signing-time: 
`authentic signing time` is a valid concept only under signing scheme [`notary.x509.signingAuthority`](https://github.com/notaryproject/specifications/blob/main/specs/signing-scheme.md/#notaryx509signingauthority). Therefore, for other signing schemes, this function should return an error.
Resolves #38

fix: fix `signerInfo.authenticSigningTime` according to spec

---

signature/cose/fuzz_test.go
signature/jws/fuzz_test.go

Moves two fuzz tests upstream from here:
1. https://github.com/cncf/cncf-fuzzing/blob/main/projects/notary/fuzz_cose.go
2. https://github.com/cncf/cncf-fuzzing/blob/main/projects/notary/fuzz_jws.go

test(signature): add two fuzz tests

---

.github/.codecov.yml
revocation/internal/ocsp/ocsp.go
revocation/internal/ocsp/ocsp_test.go
revocation/ocsp/ocsp.go
revocation/revocation.go

This PR adds `context` to OCSP revocation check.
Resolves #223

fix: ocsp revocation check with context

---

revocation/crl/fetcher_test.go
revocation/internal/crl/crl_test.go
revocation/internal/ocsp/ocsp_test.go
revocation/ocsp/ocsp_test.go
revocation/revocation_test.go
testhelper/certificatetest.go

Fix:
- added mocked HTTP client for a test case of revocation package
- replaced `*.com` with `*.test` to avoid mentioning a real domain in testing URL
NOTE: `.test` is a reserved domain for testing in RFC 2606

fix(test): test cases with `example.com` URL

---

revocation/crl/fetcher.go
revocation/internal/ocsp/ocsp.go
revocation/internal/ocsp/ocsp_test.go

Corresponding spec change: https://github.com/notaryproject/specifications/pull/319

fix: revocation response status code should be 200

---

go.mod
go.sum

This PR bumps up tspclient-go to its newest release version.

bump: bump up dependencies

---

Makefile

Fix:
- update the command to search script file in `.` instead of `scripts/` folder to avoid returning an error.

fix: `check-line-endings` command of Makefile
